// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TextWrapper from "../components/TextWrapper.bs.js";
import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";

function EnterMobileNumber(props) {
  return JsxRuntime.jsx(ReactNative.View, {
              style: {
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: Caml_option.some(JsxRuntime.jsx(TextWrapper.make, {
                        text: "Enter Mobile Number",
                        textType: "HeadingBold"
                      }))
            });
}

var make = EnterMobileNumber;

export {
  make ,
}
/* TextWrapper Not a pure module */
