// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Space from "../components/Space.bs.js";
import * as Reanimated from "../externalModules/Reanimated.bs.js";
import * as TextWrapper from "../components/TextWrapper.bs.js";
import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactNativeReanimated from "react-native-reanimated";

function EnterMobileNumber$IncreaseWidthAnimation(props) {
  var width = ReactNativeReanimated.useSharedValue(100);
  var handlePressToIncreaseWidth = function (param) {
    width.value = Reanimated.withSpring(width.value + 100, undefined, undefined, undefined);
  };
  var animatedStyles = ReactNativeReanimated.useAnimatedStyle(function () {
        return {
                width: width.value
              };
      });
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(TextWrapper.make, {
                      text: "Increase width Animation",
                      textType: "HeadingBold"
                    }),
                JsxRuntime.jsx(Space.make, {}),
                JsxRuntime.jsx(Reanimated.View.make, {
                      style: [
                        animatedStyles,
                        {
                          backgroundColor: "violet",
                          borderRadius: 10,
                          height: 60
                        }
                      ]
                    }),
                JsxRuntime.jsx(ReactNative.Button, {
                      onPress: handlePressToIncreaseWidth,
                      title: "Click me"
                    })
              ]
            });
}

var IncreaseWidthAnimation = {
  make: EnterMobileNumber$IncreaseWidthAnimation
};

function EnterMobileNumber(props) {
  return JsxRuntime.jsxs(Reanimated.View.make, {
              style: {
                alignItems: "center",
                flex: 1
              },
              children: [
                JsxRuntime.jsx(Space.make, {
                      height: 60
                    }),
                JsxRuntime.jsx(TextWrapper.make, {
                      text: "React Native Animations",
                      textType: "HeadingBold"
                    }),
                JsxRuntime.jsx(Space.make, {
                      height: 60
                    }),
                JsxRuntime.jsx(EnterMobileNumber$IncreaseWidthAnimation, {})
              ]
            });
}

var make = EnterMobileNumber;

export {
  IncreaseWidthAnimation ,
  make ,
}
/* Space Not a pure module */
