// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Space from "../components/Space.bs.js";
import * as React from "react";
import * as BirdgeLogo from "../imagesAndSvg/BirdgeLogo.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TextWrapper from "../components/TextWrapper.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as CustomButton from "../components/CustomButton.bs.js";
import * as ReactNative from "react-native";
import * as GettingStartted1 from "../imagesAndSvg/GettingStartted1.bs.js";
import * as GettingStartted2 from "../imagesAndSvg/GettingStartted2.bs.js";
import * as GettingStartted3 from "../imagesAndSvg/GettingStartted3.bs.js";
import * as GettingStartted4 from "../imagesAndSvg/GettingStartted4.bs.js";
import * as ReactNativeSvg from "react-native-svg";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import ReactNativeReanimatedCarousel from "react-native-reanimated-carousel";

var defaultVal = {
  heading: "",
  subHeading: "",
  svgString: ""
};

var carouselItems = [
  {
    heading: "The fastest ride booking app is here!",
    subHeading: "Our speedy booking process means you get a ride quickly and easily.",
    svgString: GettingStartted1.svg
  },
  {
    heading: "Dedicated Safety Center",
    subHeading: "24X7 self serve feature and SOS for  emergency support",
    svgString: GettingStartted2.svg
  },
  {
    heading: "Inclusive and accessible, for everyone!",
    subHeading: "We strive to provide all our users an even & equal experience.",
    svgString: GettingStartted3.svg
  },
  {
    heading: "Be a part of the Open Mobility Revolution!",
    subHeading: "Our data and product roadmap are transparent for all.",
    svgString: GettingStartted4.svg
  }
];

function GettingStarted$RenderItem(props) {
  var index = props.index;
  var carouselItems = props.carouselItems;
  var match = React.useState(function () {
        return true;
      });
  var setLoading = match[1];
  React.useEffect((function () {
          setLoading(function (param) {
                return false;
              });
        }), []);
  return JsxRuntime.jsxs(ReactNative.View, {
              style: {
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: [
                match[0] ? JsxRuntime.jsx(ReactNative.ActivityIndicator, {
                        style: {
                          height: Style$ReactNative.pct(75),
                          width: Style$ReactNative.pct(100)
                        }
                      }) : JsxRuntime.jsx(ReactNativeSvg.SvgXml, {
                        xml: Core__Option.getOr(carouselItems[index], defaultVal).svgString,
                        width: "100%",
                        height: "75%",
                        fill: "red",
                        onError: (function () {
                            
                          }),
                        onLoad: (function () {
                            setLoading(function (param) {
                                  return false;
                                });
                          })
                      }),
                JsxRuntime.jsx(Space.make, {}),
                JsxRuntime.jsxs(ReactNative.View, {
                      style: {
                        alignItems: "center",
                        justifyContent: "center",
                        paddingHorizontal: 20
                      },
                      children: [
                        JsxRuntime.jsx(TextWrapper.make, {
                              text: Core__Option.getOr(carouselItems[index], defaultVal).heading,
                              textType: "HeadingBold"
                            }),
                        JsxRuntime.jsx(Space.make, {}),
                        JsxRuntime.jsx(TextWrapper.make, {
                              text: Core__Option.getOr(carouselItems[index], defaultVal).subHeading,
                              textType: "Subheading"
                            })
                      ]
                    })
              ]
            });
}

var RenderItem = {
  make: GettingStarted$RenderItem
};

function GettingStarted(props) {
  var navigation = props.navigation;
  return JsxRuntime.jsxs(ReactNative.View, {
              style: {
                backgroundColor: "#F5EDFF",
                alignItems: "center",
                flex: 1,
                justifyContent: "space-between"
              },
              children: [
                JsxRuntime.jsxs(ReactNative.View, {
                      style: {
                        alignItems: "center"
                      },
                      children: [
                        JsxRuntime.jsx(Space.make, {
                              height: 70
                            }),
                        JsxRuntime.jsx(ReactNativeSvg.SvgXml, {
                              xml: BirdgeLogo.svg,
                              width: "40%",
                              height: "10%",
                              fill: "red",
                              onError: (function () {
                                  
                                }),
                              onLoad: (function () {
                                  
                                })
                            }),
                        JsxRuntime.jsx(ReactNative.View, {
                              style: {
                                flexShrink: 1,
                                height: ReactNative.Dimensions.get("screen").height / 1.6
                              },
                              children: Caml_option.some(JsxRuntime.jsx(ReactNativeReanimatedCarousel, {
                                        loop: true,
                                        width: ReactNative.Dimensions.get("screen").width,
                                        height: ReactNative.Dimensions.get("screen").height / 1.6,
                                        autoPlay: true,
                                        autoPlayInterval: 2500,
                                        data: carouselItems,
                                        scrollAnimationDuration: 1000,
                                        onSnapToItem: (function (param) {
                                            
                                          }),
                                        renderItem: (function (param) {
                                            return JsxRuntime.jsx(GettingStarted$RenderItem, {
                                                        carouselItems: carouselItems,
                                                        index: param.index
                                                      });
                                          })
                                      }))
                            })
                      ]
                    }),
                JsxRuntime.jsx(ReactNative.View, {
                      style: {
                        paddingHorizontal: 15
                      },
                      children: Caml_option.some(JsxRuntime.jsx(CustomButton.make, {
                                text: "Get Started",
                                onPress: (function (param) {
                                    navigation.navigate("EnterMobileNumber");
                                  }),
                                borderWidth: 0,
                                borderRadius: 8
                              }))
                    }),
                JsxRuntime.jsx(Space.make, {})
              ]
            });
}

var make = GettingStarted;

export {
  defaultVal ,
  carouselItems ,
  RenderItem ,
  make ,
}
/* Space Not a pure module */
