// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SplashLogo from "../imagesAndSvg/SplashLogo.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Mapbgforsplash from "../imagesAndSvg/Mapbgforsplash.bs.js";
import * as SplashJuspayLogo from "../imagesAndSvg/SplashJuspayLogo.bs.js";
import * as ReactNativeSvg from "react-native-svg";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import ReactNativeLinearGradient from "react-native-linear-gradient";

function SplashScreen(props) {
  return JsxRuntime.jsxs(ReactNativeLinearGradient, {
              start: {
                x: 0.5,
                y: 0.5
              },
              end: {
                x: 1,
                y: 0.47
              },
              locations: [
                0.1,
                0.2,
                0.4,
                0.7,
                0.9
              ],
              colors: [
                "#7435FC",
                "#7A39FB",
                "#8D45FA",
                "#AB59F8",
                "#CA6DF6"
              ],
              style: {
                backgroundColor: "#7435FC",
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: [
                JsxRuntime.jsx(ReactNativeSvg.SvgXml, {
                      xml: Mapbgforsplash.svg,
                      width: "100%",
                      height: "100%",
                      fill: "red",
                      onError: (function () {
                          
                        }),
                      onLoad: (function () {
                          
                        })
                    }),
                JsxRuntime.jsxs(ReactNative.View, {
                      style: {
                        alignItems: "center",
                        flex: 1,
                        height: Style$ReactNative.pct(100),
                        justifyContent: "center",
                        position: "absolute",
                        width: Style$ReactNative.pct(100)
                      },
                      children: [
                        JsxRuntime.jsx(ReactNativeSvg.SvgXml, {
                              xml: SplashLogo.svg,
                              width: "70%",
                              height: "100%",
                              fill: "red",
                              onError: (function () {
                                  
                                }),
                              onLoad: (function () {
                                  
                                })
                            }),
                        JsxRuntime.jsx(ReactNative.View, {
                              style: {
                                alignItems: "center",
                                flex: 1,
                                height: Style$ReactNative.pct(100),
                                justifyContent: "flex-end",
                                position: "absolute",
                                width: Style$ReactNative.pct(100)
                              },
                              children: Caml_option.some(JsxRuntime.jsx(ReactNativeSvg.SvgXml, {
                                        xml: SplashJuspayLogo.svg,
                                        width: "25%",
                                        height: "20%",
                                        fill: "red",
                                        onError: (function () {
                                            
                                          }),
                                        onLoad: (function () {
                                            
                                          })
                                      }))
                            })
                      ]
                    })
              ]
            });
}

var make = SplashScreen;

export {
  make ,
}
/* react-native Not a pure module */
