// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Space from "../components/Space.bs.js";
import * as CustomButton from "../components/CustomButton.bs.js";
import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";

function SplashScreen(props) {
  var navigation = props.navigation;
  return JsxRuntime.jsxs(ReactNative.View, {
              style: {
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: [
                JsxRuntime.jsx(ReactNative.Text, {
                      children: "Hello From SplashScreen"
                    }),
                JsxRuntime.jsx(Space.make, {}),
                JsxRuntime.jsx(CustomButton.make, {
                      text: "Navigate to Screen",
                      onPress: (function (param) {
                          navigation.navigate("Modal");
                        }),
                      borderWidth: 0
                    }),
                JsxRuntime.jsx(Space.make, {}),
                JsxRuntime.jsx(CustomButton.make, {
                      text: "Navigate to Screen",
                      onPress: (function (param) {
                          navigation.navigate("Modal");
                        }),
                      borderWidth: 0
                    })
              ]
            });
}

var make = SplashScreen;

export {
  make ,
}
/* Space Not a pure module */
