// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as ReactNative from "react-native";

function useIsDarkMode() {
  var match = Core__Option.getOr(Caml_option.nullable_to_opt(ReactNative.useColorScheme()), "light");
  return match !== "light";
}

export {
  useIsDarkMode ,
}
/* react-native Not a pure module */
