// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";

function Space(props) {
  var __height = props.height;
  var __width = props.width;
  var width = __width !== undefined ? __width : 15;
  var height = __height !== undefined ? __height : 15;
  return JsxRuntime.jsx(ReactNative.View, {
              style: {
                height: height,
                width: width
              }
            });
}

var make = Space;

export {
  make ,
}
/* react-native Not a pure module */
