// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as SplashScreen from "../screens/SplashScreen.bs.js";
import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";
import * as Stack$ReactNavigation from "rescript-react-navigation/src/Stack.bs.js";
import * as Native from "@react-navigation/native";

function NavigationRouter$ModalScreen(props) {
  return JsxRuntime.jsx(ReactNative.Text, {
              children: "Hello From Modal"
            });
}

var ModalScreen = {
  make: NavigationRouter$ModalScreen
};

var include = Stack$ReactNavigation.Make({});

var $$Navigator = include.$$Navigator;

var $$Screen = include.$$Screen;

function NavigationRouter$MainStackScreen(props) {
  return JsxRuntime.jsx($$Navigator.make, {
              screenOptions: (function (param) {
                  return {
                          headerShown: false
                        };
                }),
              children: Caml_option.some(JsxRuntime.jsx($$Screen.make, {
                        name: "SplashScreen",
                        component: SplashScreen.make
                      }))
            });
}

var MainStackScreen_Group = include.Group;

var MainStackScreen = {
  $$Navigator: $$Navigator,
  $$Screen: $$Screen,
  Group: MainStackScreen_Group,
  make: NavigationRouter$MainStackScreen
};

var include$1 = Stack$ReactNavigation.Make({});

var $$Navigator$1 = include$1.$$Navigator;

var $$Screen$1 = include$1.$$Screen;

function NavigationRouter$RootStackScreen(props) {
  return JsxRuntime.jsx(Native.NavigationContainer, {
              children: JsxRuntime.jsxs($$Navigator$1.make, {
                    screenOptions: (function (param) {
                        return {
                                presentation: "modal",
                                headerShown: false
                              };
                      }),
                    children: [
                      JsxRuntime.jsx($$Screen$1.make, {
                            name: "Main",
                            component: NavigationRouter$MainStackScreen
                          }),
                      JsxRuntime.jsx($$Screen$1.make, {
                            name: "Modal",
                            children: (function (param) {
                                return JsxRuntime.jsx(NavigationRouter$ModalScreen, {
                                            navigation: param.navigation,
                                            route: param.route
                                          });
                              })
                          })
                    ]
                  })
            });
}

var RootStackScreen_Group = include$1.Group;

var RootStackScreen = {
  $$Navigator: $$Navigator$1,
  $$Screen: $$Screen$1,
  Group: RootStackScreen_Group,
  make: NavigationRouter$RootStackScreen
};

export {
  ModalScreen ,
  MainStackScreen ,
  RootStackScreen ,
}
/* include Not a pure module */
