// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NavigationRouter from "./Hooks/NavigationRouter.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(NavigationRouter.RootStackScreen.make, {});
}

var make = App;

export {
  make ,
}
/* NavigationRouter Not a pure module */
