// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as NavigationRouter from "./navigation/NavigationRouter.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(ReactNative.SafeAreaView, {
              style: {
                flex: 1
              },
              children: Caml_option.some(JsxRuntime.jsx(NavigationRouter.RootStackScreen.make, {}))
            });
}

var make = App;

export {
  make ,
}
/* react-native Not a pure module */
